### ISSUE TITLE
side-by-side模式各种显示错位问题的解决方法

### ISSUE THREAD

**Issue by Simoncxm** [ddchef/vue-code-diff#39]
### 1、左右两侧上方对不齐
![image](https://user-images.githubusercontent.com/48645710/104679545-e3609c80-5728-11eb-8e00-527d4611719b.png)
解决方法：
在style加上以下css
``` css
.d2h-files-diff {
  position: relative;
}

.d2h-files-diff > .d2h-file-side-diff ~ .d2h-file-side-diff {
  position: absolute;
}
```
效果：
![image](https://user-images.githubusercontent.com/48645710/104679767-5d912100-5729-11eb-8a6e-a11af784b923.png)
### 2、左右两侧若出现删除代码和新增代码时高度不一致
![image](https://user-images.githubusercontent.com/48645710/104679846-874a4800-5729-11eb-9c43-0d0227239ad8.png)
![image](https://user-images.githubusercontent.com/48645710/104679861-8d402900-5729-11eb-9995-a7c326a8878b.png)
![image](https://user-images.githubusercontent.com/48645710/104679873-95986400-5729-11eb-9d6b-627cd498f3f8.png)
解决方法：
在style加上以下css
``` css
.d2h-code-side-emptyplaceholder {
  max-height: 16px;
}

.d2h-code-side-line {
  display: block;
}

.d2h-code-side-line.d2h-info {
  height: 15px;
}
```
效果：
![image](https://user-images.githubusercontent.com/48645710/104679955-bf518b00-5729-11eb-9395-2e2038f45c0f.png)

#7 #11 @ddchef
