### ISSUE TITLE
比对左右不对齐问题

### ISSUE THREAD

**Issue by chengcgj** [ddchef/vue-code-diff#58]
您好，使用side-by-side模式时，左右第一行无法对齐，看官方示例，右侧div层有一个名为d2h-info的class，
![image](https://user-images.githubusercontent.com/86461035/123376699-81507100-d5bd-11eb-918a-d82aec9b57ec.png)
我的项目渲染后，这个div缺少这个class，导致这行没有高度
![image](https://user-images.githubusercontent.com/86461035/123376833-b8bf1d80-d5bd-11eb-9522-e2072c2a84d5.png)

使用版本是1.2.0

**Comment by Shimada666** [comment]
是 1.2.0 版本的问题
可以回退版本，或全局加载 css 解决
```css
.d2h-wrapper .d2h-code-side-line,
.d2h-wrapper .d2h-code-line {
  display: inline-block;
  width: auto;
}
```
也可以提一下 pr 修复
